# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9e6206522dd6db5e895b12e48ac98201fa1bda1de2cb7b24b5e5dd36931b5b7b54e6c1590f1fdd5128ad8f7620c5b4b6622eab0e548835a2c93a73c5298b55b

test:
  secret_key_base: b52819989101f7273b2f073440ad23a0c2db3bde03f8454896396f59d6b9ef14b3500da632c469903bdfdaa9ee8bc396e7b8d2b3c40f3c4d3c295d3c18924858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
